spring:
  application:
    name: springboot-rabbitmq-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
server:
  port: 8090
  servlet:
    context-path: /myapplication